### ISSUE TITLE
Enable the demo site for Firefox

### ISSUE THREAD

**Issue by rathboma** [jarek-foksa/xel#100]
Since early 2020, firefox has had support for native components, so the demo site should work now!

**Comment by rathboma** [comment]
I think it's just the `dialog` element still not supported by firefox, that should be easy to polyfill.

https://github.com/GoogleChrome/dialog-polyfill?

**Comment by jarek-foksa** [comment]
I tried to polyfill the `<dialog>` element under Safari but I gave up because I couldn't make it work inside shadow trees without ugly hacks. I also recall trying the polyfill by Google but it would fail even with the most basic examples.

**Comment by rathboma** [comment]
how much of Xel requires `dialog`? Could it just be enabled, but with a warning for elements that require it?

**Comment by jarek-foksa** [comment]
There are no Xel elements that would explicitly require `<dialog>`.

Still, I don't really have the time to deal with Firefox-specific bugs, so even with proper `<dialog>` implementation I would not support that browser.
