### ISSUE TITLE
attachShadow mode closed

### ISSUE THREAD

**Issue by ghstng** [jarek-foksa/xel#101]
First off, great library -- implementing (forked version currently) in 
https://github.com/beekeeper-studio/beekeeper-studio.  

With mode 'closed' on all the elements, xel can be difficult to theme -- especially concerning dark themes (where x-menu, for example, has a hard-coded white background).  Just curious if this can be opened up -- or if you have a strong reason for the current implementation. 

:metal::metal:

**Comment by jarek-foksa** [comment]
`<x-menu>` does not have a hard-coded white background, themes can (and do) override it with their own stylings.

BTW, I will be adding [dark themes and rewriting existing themes](https://boxy-svg.com/ideas/90/preferences-theme-setting) later this year.

**Comment by ghstng** [comment]
rgr
