### ISSUE TITLE
How to programatically open the context menu?

### ISSUE THREAD

**Issue by rathboma** [jarek-foksa/xel#104]
I have an app with some HTML I do not control, but I do get a callback for 'rightClick', and I'd like to open a Xel context menu.

Is this possible?

Thanks for your work!

**Comment by jarek-foksa** [comment]
This should be possible, please check https://gist.github.com/jarek-foksa/fd67b58472492f722576bdbfa62e68b0 which demonstrates how to open a menu programatically.
