### ISSUE TITLE
x-numberinput doesn't hold value

### ISSUE THREAD

**Issue by YassienW** [jarek-foksa/xel#105]
If you change the value of an x-numberinput, you have to unfocus the field in order for the value property to be updated.
This is very inconvenient when the user puts in a value then clicks on a start button for example.

**Comment by jarek-foksa** [comment]
I will fix this bug in Xel version 1.0 which should appear till then end of this year (I'm currently developing it in a private repo).

**Comment by YassienW** [comment]
Perfect!

**Comment by jarek-foksa** [comment]
Fixed in version 0.9.1. Sorry for the long delay.
