### ISSUE TITLE
Is there any way to access the value inside of the different form components?

### ISSUE THREAD

**Issue by ferretwithaberet** [jarek-foksa/xel#106]
Literally what the title says, I want to be able to access the value of components like `x-input`, I was able to do my own thing for `x-checkbox`, `x-switch`, `x-radio` and `x-select` but I cannot figure it out how to do it for components like `x-input` as the value is stored somewhere inside of the shadow dom which is closed...

**Comment by jarek-foksa** [comment]
`x-input` does not have a "value" attribute, but it has a "value" property which you should be able to access from JavaScript. I will document it when Xel 1.0 gets released in January.

**Comment by jarek-foksa** [comment]
The new project website now documents the JavaScript API for each element.

**Comment by phamduylong** [comment]
This code below logged undefined. Can you explain how this works? @jarek-foksa 
```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta name="xel-theme" content="../node_modules/xel/themes/adwaita.css">
    <meta name="xel-iconsets" content="../node_modules/xel/iconsets/fluent.svg">
    <meta name="xel-accent-color" content="blue">
    <script src="../node_modules/xel/xel.js" type="module"></script>
    <meta charset="UTF-8">
    <link href="../styles/styles.css" rel="stylesheet">
    <title>Hello World!</title>
  </head>
  <body>
    <form id="login-panel">
      <h1>Login</h1>
      <span class="input-row">
        <x-input type="text" id="uid" value="" required>
          <x-icon href="#person"></x-icon>
          <x-label>Username</x-label>
        </x-input>
      </span>
      <span class="input-row">
        <x-input type="password" id="pwd" value="" required>
          <x-icon href="#lock"></x-icon>
          <x-label>Password</x-label>
        </x-input>
      </span>
      <span id="login-submit-btn-row">
        <x-button type="submit" id="login-submit-btn">Submit</x-button>
      </span>
    </form>
  </body>
  <script>
    const uid = document.querySelector('#uid').value;
    console.log("UID: ", uid);
  </script>
</html>
```

**Comment by jarek-foksa** [comment]
I think you have to wait until the custom element gets defined before you access its properties, try using `document.addEventListener("load", () => {/* your code */});` or `customElements.whenDefined("x-input").then(() => {/* your code */});`.
