### ISSUE TITLE
Having trouble with x-select toggled please anyone help me.

### ISSUE THREAD

**Issue by abyjohnson5** [jarek-foksa/xel#107]
I followed https://xel-toolkit.org/setup these steps and while using x-select with toggled there is no pre-selection is showing up. and when trying to pick one from the options console shows an error "Uncaught (in promise) TypeError: Cannot read property 'getBoundingClientRect' of undefined at xel.min.js:11563"

**Comment by jarek-foksa** [comment]
How did you declare the select widget? If possible please attach the markup here.

**Comment by Aby-Johnson** [comment]
<x-select>
  <x-menu>
    <x-menuitem value="australia">
      <x-label>Australia</x-label>
    </x-menuitem>

    <x-menuitem value="canada" toggled>
      <x-label>Canada</x-label>
    </x-menuitem>

    <x-menuitem value="ireland" disabled>
      <x-label>Ireland</x-label>
    </x-menuitem>

    <x-menuitem value="new-zealand">
      <x-label>New Zealand</x-label>
    </x-menuitem>

    <x-menuitem value="uk">
      <x-label>United Kingdom</x-label>
    </x-menuitem>

    <x-menuitem value="usa">
      <x-label>United States</x-label>
    </x-menuitem>
  </x-menu>
</x-select>

All as same described in the official doc

**Comment by jarek-foksa** [comment]
So it works for you on https://xel-toolkit.org/elements/x-select, but now when you include the same markup on your website? Are you using some virtual DOM framework to render the views?

**Comment by jarek-foksa** [comment]
The code you attached is not complete, note that all <x-menuitem> elements must be inside <x-menu>.

**Comment by Aby-Johnson** [comment]
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="node_modules/xel/themes/material.css">
  <link rel="stylesheet" href="css/styles.css?v=1.0">

</head>

<body>
    <x-select>
  <x-menu>
    <x-menuitem value="australia">
      <x-label>Australia</x-label>
    </x-menuitem>

    <x-menuitem value="canada" toggled>
      <x-label>Canada</x-label>
    </x-menuitem>

    <x-menuitem value="ireland" disabled>
      <x-label>Ireland</x-label>
    </x-menuitem>

    <x-menuitem value="new-zealand">
      <x-label>New Zealand</x-label>
    </x-menuitem>

    <x-menuitem value="uk">
      <x-label>United Kingdom</x-label>
    </x-menuitem>

    <x-menuitem value="usa">
      <x-label>United States</x-label>
    </x-menuitem>
  </x-menu>
</x-select>
    
    
  <script src="node_modules/xel/xel.min.js"></script>
  <script src="js/scripts.js"></script>
</body>
</html>

**Comment by Aby-Johnson** [comment]
![Uploading IMG_20201203_110418.jpg…]()

**Comment by jarek-foksa** [comment]
Xel project underwent a major rewrite recently. If you can still reproduce this issue, please report it on https://xel-toolkit.org/issues.
