### ISSUE TITLE
[Feature request] Tauri support

### ISSUE THREAD

**Issue by KaKi87** [jarek-foksa/xel#114]
Hello,

[Tauri](https://tauri.app/) is an Electron alternative that [uses different engines depending on operating system](https://github.com/tauri-apps/wry#platform-specific-notes) :
- [WebKitGTK](https://webkitgtk.org/) on Linux
- [WebKit](https://webkit.org/) on Mac
- [Edge WebView2](https://developer.microsoft.com/microsoft-edge/webview2/) on Windows

Since it is [lighter weight and less memory-consuming](https://github.com/tauri-apps/tauri#comparison-between-tauri-and-electron), it would be nice for Xel to support it.

Thanks !

**Comment by Bellisario** [comment]
@KaKi87 I think this is impossible for now by just reading the FAQ on documentation site, where are listed all platforms supported: WebKit isn't for now and you can currently use only with Windows (I don't know if WebKitGTK is supported, but I don't think since it's built on top of WebKit).

Anyway, maybe the Xel developer decide to bring it also on WebKit...

**Comment by jarek-foksa** [comment]
I would like to support WebKit at some point in future, currently there is at least one important API ([Constructable Stylesheets](https://caniuse.com/?search=Constructable%20Stylesheets)) missing.

**Comment by KaKi87** [comment]
That's only needed for the `<meta name="xel-theme" content="...">` tag, right ?

**Comment by jarek-foksa** [comment]
[Constructable Stylesheets](https://caniuse.com/?search=Constructable%20Stylesheets) and [adoptedStyleSheets](https://caniuse.com/mdn-api_document_adoptedstylesheets) APIs are needed for dynamic theme switching, no matter whether you use meta tags or JS API.

**Comment by KaKi87** [comment]
I didn't know there was a JS API, where did I miss it ?

But yes, I guessed that `meta` tags would be watched by JS to dynamically switch themes.

So, if dynamic switching is the only feature that require those APIs, everything else can still work using CSS imports, right ?

**Comment by jarek-foksa** [comment]
Actually, dynamic theme switching could be implemented without these APIs (as it was done in earlier versions of Xel), but it would be much slower.

**Comment by jarek-foksa** [comment]
The JS API for theme switching is not currently documented, you can use it like this:

```js
import Xel from "/node_modules/xel/xel.js";
Xel.theme = "/themes/adwaita";
```

**Comment by KaKi87** [comment]
What about allowing usage of Xel even when dynamic switching is unavailable ?
Especially when using a JS framework, we don't necessarily need Xel to handle that.
Most multi-theme CSS framework don't and it's fine.

**Comment by jarek-foksa** [comment]
It would still require many adjustments. I would rather prefer to wait for Apple to implement the missing APIs or write a polyfill for them.

**Comment by KaKi87** [comment]
Alright, then I'll be waiting for either to happen, to release my Tauri app on Linux.

**Comment by jarek-foksa** [comment]
I added WebKit support in Xel version 0.20.0. Still, it's probably not a good idea to use it with Tauri as only the latest version of WebKit (605.1.15, same as Safari 16.4) is supported.
