### ISSUE TITLE
Stable API

### ISSUE THREAD

**Issue by jarek-foksa** [jarek-foksa/xel#12]
Public API of each element has to be reviewed and adjusted in case there are any inconsistencies. Then release the first stable version of Xel (1.0.0).

Inspirations:

- [Fabric](https://developer.microsoft.com/en-us/fabric#/components)
- [Polymer](https://elements.polymer-project.org/browse?package=paper-elements)
- [MUI](https://www.muicss.com/)
- [Ant Design](https://ant.design/docs/react/introduce)
- [Angular Material](https://material.angularjs.org/latest/api)
- [Bootstrap Material](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html)
- [Material UI](http://www.material-ui.com/)
- [Material Design Lite](https://getmdl.io/components/index.html)
- [Material 2 (iOS)](https://github.com/CosmicMind/Material)
- [Materialize](http://materializecss.com)
- [Material Kit](http://demos.creative-tim.com/material-kit/components-documentation.html)
- [Flutter](https://flutter.io/widgets/)
- [Elm MDL](https://debois.github.io/elm-mdl/#buttons)
- [UI Kit](https://getuikit.com/)
- [XUL](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL)
- [Ionic](http://ionicframework.com/docs/v2/components/#overview)

**Comment by tomjamescn** [comment]
Great job!

**Comment by jarek-foksa** [comment]
I just publish the first beta version of Xel (0.9). I'm not planning to introduce any major breaking changes from now on.
