### ISSUE TITLE
<x-contextmenu>Suggestions on optimization

### ISSUE THREAD

**Issue by gjcf** [jarek-foksa/xel#122]
"`<x-contextmenu>` is a menu that appears when user clicks the right mouse button.”

Experience problems：Repeated clicking at the same position will reopen the menu, and the right-click menu will flash
Possible expectations：Click at the same location not to reopen
Expected results may：Will update native

**Comment by jarek-foksa** [comment]
I think Xel should mimic native macOS behavior here, i.e. when the context menu is already open then right-clicking should either close the menu (if the cursor has not moved) or reopen the menu at a new position (if the cursor has moved).

**Comment by gjcf** [comment]
OK。 I refer to the effect of the window system
