### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'styleMap') at #k (xel.js:1:51212)

### ISSUE THREAD

**Issue by hwqchi** [jarek-foksa/xel#126]
# What I have done
Here follows parts of my projects:

![code1](https://user-images.githubusercontent.com/6689097/220302328-0c066216-3d8a-4e14-bd81-6c0202c82257.png)
![code2](https://user-images.githubusercontent.com/6689097/220302340-5fca3a37-5e39-40ca-9fcf-7b2aa496688f.png)

# Problem
I installed the Xel according to the **Setup** steps, but I got some errors when running my projects.
Besides, the css stylesheets could not display properly.

![xel-error1](https://user-images.githubusercontent.com/6689097/220299403-172bab2e-be7a-4a5d-a0d6-ad36089c5801.png)
![xel-error1_breakpoint](https://user-images.githubusercontent.com/6689097/220299411-4c87089c-c845-4c0a-907b-9d32c74de8a1.png)

So I guess it seems have something to do with "**xel-accent-color**" meta tag.
Then, I tried to delete the line `<meta name="xel-accent-color" content="blue">`, but new errors arise: 

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim')
    at E.parse (xel.js:1:7484)
    at #k (xel.js:1:51113)

![xel-error2](https://user-images.githubusercontent.com/6689097/220299389-9b06e5f3-96f8-4dff-8e6e-39594d4d8a72.png)
![xel-error2_breakpoint](https://user-images.githubusercontent.com/6689097/220299399-1f6ba4e0-2bb6-4c46-898f-b1a8909f1929.png)

# Other Info
[Environment]
Microsoft Edge 110.0.1587.50
Windows11
Node.js 18.14.1

[Dependencies]
vite: 4.1.3
vue: ^3.2.47
xel: ^0.19.0
@vitejs/plugin-vue: ^4.0.0
electron: 23.1.0

**Comment by jarek-foksa** [comment]
The problem is caused by this line:

```html
<meta name="xel-theme" content="node_modules/xel/themes/adwaita.css">
```

Are you sure that the path `node_modules/xel/themes/adwaita.css` is actually accessible? Please also try moving `<script src="node_modules/xel/xel.js" type="module"></script>` below all `<meta>` tags.

**Comment by hwqchi** [comment]
Yes, you are literally right about this. It is the path issue that caused these errors.
But there are some problems that confused me a lot.
I moved the line `<script src="node_modules/xel/xel.js" type="module"></script>` below all `<meta>` tags. **It still won't work.**
After I did following steps below, I found something so weird.
## Solution1
![图一](https://user-images.githubusercontent.com/6689097/222035636-cc513adf-5555-46a8-ab23-78b82e571aca.png)
![图二](https://user-images.githubusercontent.com/6689097/222036793-73655538-9af9-4c5d-b7bb-7fcac66c4fa9.png)

The css is applied in the page properly. But the warnings still exsit.

## Solution2

![图三](https://user-images.githubusercontent.com/6689097/222036863-6776511e-67b7-41e1-847d-54104844e9e5.png)
![图四](https://user-images.githubusercontent.com/6689097/222036873-4e42ebc0-2b19-4aa6-96d8-0b8aee9d4ab8.png)
The css is applied in the page properly as well. But the warnings still exsit.

## Warnings
![图五](https://user-images.githubusercontent.com/6689097/222037013-3d3f1401-9f4b-4d82-96f9-634582a10942.png)


```
[Vue warn]: Failed to resolve component: x-icon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <BookMarkTable> 
  at <App>
```
I guess it might be associated with the compatibility of Vue3. Is there any solution to get rid of these warnings? 

## What confused me
I have figured it out it is the path problem that caused these errors above. Then, why would some resources, like .svg and .js files be accessible? Why .css files not? 

Thanks a lot.

**Comment by jarek-foksa** [comment]
I have never used Vue so I'm afraid I can't help you to get rid of these warnings. You seem to be using some preprocessor to compile main.js, but I have no idea what logic is used to resolve relative URLs.
