### ISSUE TITLE
Some <x-colorselect> events don't work

### ISSUE THREAD

**Issue by edgardozoppi** [jarek-foksa/xel#140]
The following events of `<x-colorselect>` element don't work.

- changestart
- changeend
- collapse

**Comment by jarek-foksa** [comment]
I can't reproduce this issue. Note that changing the display mode (RGB/HSL/HSV/etc) does not change the value and thus no events are fired.

![2024-01-10 10 07 40](https://github.com/jarek-foksa/xel/assets/193371/caa24d31-4155-46ac-b04f-e694e1c044b7)

**Comment by edgardozoppi** [comment]
I'm so sorry, I can't reproduce the issue now either. I must certainly have made a mistake before.
