### ISSUE TITLE
<x-colorselect> returns selected value in rgb(...) format in some cases

### ISSUE THREAD

**Issue by edgardozoppi** [jarek-foksa/xel#141]
When manually changing the `hsl(...)` values by directly writting in the color format selector at the bottom of the `<x-colorpicker>` the `value` property returns the color in the `rgb(...)` format instead of the `#...` format (sorry, I don't know the format names).

In order to simplify the usage of the component I think values sould always be in the same format so there is no need to deal with parsing different color formats. Maybe the output format could be configurable in another property if needed.

**Comment by jarek-foksa** [comment]
Fixed in version 0.25.2. The value in sRGB color space should be always in hex format unless you used the JavaScript API to set it.
