### ISSUE TITLE
<x-radios> don't have a change event

### ISSUE THREAD

**Issue by edgardozoppi** [jarek-foksa/xel#142]
I think it makes sense to have a `change` or `toggle` event to be able to detect and handle `value` changes, just like `<x-buttons>` have.

**Comment by jarek-foksa** [comment]
`<x-radios>` should fire the `toggle` event [when clicked](https://github.com/jarek-foksa/xel/blob/master/elements/x-radios.js#L68). If this is not working for you, please provide a sample code snippet.

**Comment by edgardozoppi** [comment]
You are right, it's working fine. The problem was that [this](https://xel-toolkit.org/elements/x-radios) page does not include the event in the documentation, so I didn't know about it.

**Comment by jarek-foksa** [comment]
I just published version 0.25.11 with updated documentation.
