### ISSUE TITLE
colorjs.io dependency is not versioned in package.json

### ISSUE THREAD

**Issue by dbrnz** [jarek-foksa/xel#149]
Line 7 of `utils/color.js` reads:
```
import ColorSpace from "../node_modules/colorjs.io/src/space.js";
```
 yet `space.js` is missing from the 0.5.* releases of `colorjs.io`. The culprit is xel's `package.json` which has:

```
"colorjs.io": "https://github.com/color-js/color.js",
```

with no version specified.

**Comment by dbrnz** [comment]
In fact `colorjs.io` is available on npm, so why pull it directly from GitHub?

**Comment by jarek-foksa** [comment]
[Fixed](https://github.com/jarek-foksa/xel/commit/7853e1ebb7ec4d5c5c7703d5c1d225580b866327) in Xel version 0.28.9.

Dev version of colorjs.io is needed because the current stable version does not support okHSV and okHSL spaces yet.
