### ISSUE TITLE
System color Theme

### ISSUE THREAD

**Issue by Kilian** [jarek-foksa/xel#15]
CSS has the option to pick system default colors and fonts, detailed here: https://www.sitepoint.com/css-system-styles/ implementing the use of these colors and fonts will get you additional integration for relatively little effort!

**Comment by jarek-foksa** [comment]
According to the [CSS Color Module Level 4 spec](https://drafts.csswg.org/css-color-4/#system-colors) those keywords should have hard-coded values which does not make them that useful. Are you able to distinguish between the Blue and Graphite macOS appearances using them?

**Comment by Kilian** [comment]
I think Chrome indeed already uses hardcoded values (firefox follows my system colors) so it might be less useful in that regard. But: worst case is you have a nice abstraction on which to base your color names, and the defaults will be colors that work well together (undefined environments/styles would get that, and if you specifically go for "the macOS" style, you could overlay the current macOS styling)

They have been deprecated in CSS module 4, but the CSS3 replacement "[Appearance](https://developer.mozilla.org/en/docs/Web/CSS/-moz-appearance)", whilst not fully supported, could also help for example to style buttons on macOS.

**Comment by jarek-foksa** [comment]
In my opinion each theme should define its own set of configurable colors that follows the naming conventions used by corresponding HIG (like "primary", "secondary" and "accent" in Material Design).

Then Electron users could override those variables with values retrieved from the system using [systemPreferences.getColor(color)](https://electron.atom.io/docs/api/system-preferences/#systempreferencesgetcolorcolor-windows) and [systemPreferences.getAccentColor()](https://electron.atom.io/docs/api/system-preferences/#systempreferencesgetaccentcolor-windows) APIs:

```js
document.body.style.setProperty("--accent-color", systemPreferences.getAccentColor());
```

Currently those APIs work only on Windows, but I don't see any reason why they couldn't be extended to macOS and Linux in future.

**Comment by Kilian** [comment]
I get wanting to follow the HIGs in naming, and using the Electron apis like that sounds like a good idea as well! :)

**Comment by jarek-foksa** [comment]
Done in Xel 0.9.
