### ISSUE TITLE
CSP Error

### ISSUE THREAD

**Issue by joelrechin** [jarek-foksa/xel#151]
I get the following console error when starting my Electron app:

xel.js:1 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-bHgN9XKsPBYuE+h0MFPVVbycccJ4eLuTnTNgGiVTGJ0='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

<script src="../node_modules/xel/xel.js" type="module"></script> was placed in the <head> as directed, also at the end of the body as Electron has directed other script files to go.

**Comment by jarek-foksa** [comment]
To use Xel you have to relax your Content Security Policy to [allow inline styles](https://github.com/jarek-foksa/xel/blob/ba646f04a8d6b7e80fd988ab0f196ba1e5d4dc52/portal.html#L22-L24).
