### ISSUE TITLE
x-grid

### ISSUE THREAD

**Issue by malublu** [jarek-foksa/xel#19]
a simple grid system

**Comment by jarek-foksa** [comment]
Do you mean something like https://material.io/guidelines/components/grid-lists.html#grid-lists-usage? I think this type of layout is already very easy to achieve with <x-box>.

**Comment by malublu** [comment]
No something like: https://purecss.io/grids/

**Comment by jarek-foksa** [comment]
Looks like GTK also implements this type of widget: https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Grid.html

I will have to research this further, I'm not sure yet whether it has any advantages over `<x-box>` (flexbox model).

**Comment by jarek-foksa** [comment]
I'm no longer planning to implement this feature as it seems inferior to the flexbox model (at least when laying out widgets).
