### ISSUE TITLE
Syntax Error Loading HTML file

### ISSUE THREAD

**Issue by Jaliborc** [jarek-foksa/xel#20]
Xel has been working great for me on one of my Windows 7 machines. Yet, I tried loading it on a different Windows 10 machine today. I get the following error when loading the html file: 

> xel.min.html:1 Uncaught SyntaxError: missing ) after argument list

I have tried installing different versions from npm (0.0.12 to 0.0.14). They all give this error. I am using xel on the same project with the same code on both machines, so I don't know where to go from here.

**Comment by jarek-foksa** [comment]
Please make sure that in your `package.json` you have `"xel": "^0.0.14"`, then remove  `<your_project_dir>/node_modules/xel/` directory and run `npm install`.

If it does not solve the problem, let me know whether `<your_project_dir>/node_modules/xel/xel.min.html` file actually exist.

**Comment by Heziode** [comment]
I had the same problem with electron version 1.6.2.
After update to 1.6.6, problem is solved.

**Comment by jarek-foksa** [comment]
@Heziode Thanks for letting me know. @Jaliborc Please reopen the issue if you can still reproduce it.
