### ISSUE TITLE
costume url

### ISSUE THREAD

**Issue by malublu** [jarek-foksa/xel#21]
```
@import url(https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i);
@import url(https://fonts.googleapis.com/css?family=Roboto+Mono:400,400i,700,700i);
```

should be local for electron (desktop applications).

https://github.com/jarek-foksa/xel/blob/5e8d5564792e9d16089fb78975b311566ed15150/elements/x-icon.js#L14

Url path should be costumizable, if you change you app directory like this:

```
<link rel="import" href="../node_modules/xel/xel.min.html">
<link rel="stylesheet" href="../node_modules/xel/stylesheets/material.theme.css">
```

**Comment by jarek-foksa** [comment]
I have adjusted the font links so that locally installed Roboto fonts are used if preset.

You must use `<link rel="import" href="node_modules/xel/xel.min.html">` to import Xel. I have no plans for allowing anything else until the code is migrated to ES6 modules.
