### ISSUE TITLE
Add Marko support

### ISSUE THREAD

**Issue by Heziode** [jarek-foksa/xel#22]
Hi, I work one electron project using [Marko](http://markojs.com/).

When I compile (with webpack), it failed because x-button,etc are not defined templates.

Solution I found ?

Just create a `marko.json` at the root of project and describe all tags with attributes.
Exemple : 
```json
{
  "tags": {
    "x-input": {
      "attributes": {
        "type": "string"
      }
    },
    "x-icon": {
      "attributes": {
        "name": "string",
        "iconset": "string"
      }
    },
    "x-label": {
      "attributes": {
        "data-vivaldi-spatnav-clickable": "number"
      }
    },
    "x-button": {
      "attributes": {
        "data-vivaldi-spatnav-clickable": "number"
      }
    }
  }
}
```

Possible improvement, add an `marko.json` at the root of project who discribe all tags with attributes ?

**Comment by jarek-foksa** [comment]
I would prefer to not include any framework-specific code in this repo. Please create a separate `xel-marko` project with necessary adjustments.
