### ISSUE TITLE
SyntxError:

### ISSUE THREAD

**Issue by sandor** [jarek-foksa/xel#24]
I am getting an Uncaught SyntaxError in devtools while launching my Electron project with Xel installed:

`missing ) after argument list xel.min.html:1`

Help is appreciated – would like to test out Xel...

**Comment by jarek-foksa** [comment]
1. Does the file `node_modules/xel/xel.min.html` actually exist? If you installed Xel directly from the GitHub repo rather than NPM then you should run `./project build` in order to generate that file.

2. Are you sure you are importing Xel using *exactly* the following code? `<link rel="import" href="node_modules/xel/xel.html">`

**Comment by sandor** [comment]
Hey jarek,

1. I am using the ElectronPhotonStarter project from GitHub, since I would also like to use the Header/Footer/Pane-Group from Photon

2. I have done a "npm install xel" inside my project folder in terminal

3. apparently I have got xel installed, since the xel directory is installed in node_modules – including xel.min.html

4. in my index.html I am declaring this in the head section:

```
<head>
	<title>Photon</title>

	<!-- Xel Imports -->
	<link rel="import" href="node_modules/xel/xel.min.html">
	<link rel="stylesheet" href="node_modules/xel/stylesheets/macos.theme.css">

	<link rel="stylesheet" href="./css/photon.min.css">

	<!-- Javascript -->
	<script src="./js/menu.js" charset="utf-8"></script>
</head>
```

5. even if I throw out the Photon css, I am getting the same error after running the photon project wit "npm start"

6. aree you having a clean electron project with xel only that I could use instead? Or a quick advise?

Thanks

**Comment by jarek-foksa** [comment]
I'm attaching below the smallest possible Electron demo app that uses Xel. Does it work for you? (Don't forget to run `npm install` in app dir).

[xel-electron-demo.zip](https://github.com/jarek-foksa/xel/files/1008111/xel-electron-demo.zip)

![screenshot](https://cloud.githubusercontent.com/assets/193371/26160262/0dd10a86-3b21-11e7-86a6-faeeca25dd0d.png)

**Comment by sandor** [comment]
Thanks Jarek,

1. running "npm install xel" in the project folder returns errors in terminal
2. running "electron ." will start the project in electron but again with that error

See both screenshots:


![1](https://cloud.githubusercontent.com/assets/476224/26160969/e3bb7b80-3b22-11e7-9a4e-798adacf9ec5.jpg)
![2](https://cloud.githubusercontent.com/assets/476224/26160970/e3e5ca66-3b22-11e7-94b6-22d874373c47.jpg)

**Comment by jarek-foksa** [comment]
> 1.  running "npm install xel" in the project folder returns errors in terminal

Those are not errors, just warnings about missing fields in package.json file (which are not really needed by the demo.

> 2. running "electron ." will start the project in electron but again with that error

What version of Electron and macOS are you using? The demo app works fine for me with Electron 1.7.1 and macOS 10.12.4

**Comment by sandor** [comment]
regarding the electron version see the screenshot (sorry for my ignorance, but I don't know how to get the version number via terminal)... sorry again fro the newbish things here...

My OSX is 10.11.5
![3](https://cloud.githubusercontent.com/assets/476224/26162271/9524801c-3b26-11e7-8bcf-088d48b2afdf.jpg)

**Comment by sandor** [comment]
Soyy Mate!  Have installed electron again globally "npm install -g electron". Not it seems to be running fine ;-) I think it was simply an old electron version I was using ... THANKS again!

**Comment by sandor** [comment]
BTW: are you planning something like the Head/Footer/Pane-Group like in Photon?

**Comment by jarek-foksa** [comment]
Electron 1.1.x is based on Chrome 50 which is rather old, I didn't even bother testing Xel with it. Please make sure you have installed at least Electron version 1.6.x which is based on Chrome 56.

**Comment by jarek-foksa** [comment]
> BTW: are you planning something like the Head/Footer/Pane-Group like in Photon?

I'm not sure yet, I'm planning to keep adding new elements gradually as I develop new apps that need them.
