### ISSUE TITLE
key attribute of x-shortcut conflicts with react's key attribute

### ISSUE THREAD

**Issue by rockiger** [jarek-foksa/xel#29]
It seems to me, that the *key* attribute for the x-shortcut is "misread" by react as an [identification key](https://facebook.github.io/react/docs/lists-and-keys.html#keys). This way I can't display shortcuts correctly. I can only display the modifiers, but the character of the shortcut is not shown (see picture). 

Is it possible to rename the *key* attribute to *char* or *val*?

![x-shortcut-react-conflict](https://user-images.githubusercontent.com/458677/27789320-6511d9ca-5fec-11e7-8520-c6f4cae8b4be.jpg)

FYI, I am not using react directly, but with Clojurescript and Reagent. IMO the problem should persist with JSX.

**Comment by rockiger** [comment]
Cool, thanks.

> BTW, is there a list of other attributes that have special meaning in React?

Not that I am aware of. Some work differently, but this shouldn't be a problem: https://facebook.github.io/react/docs/dom-elements.html.

With the key attribute the problem is, that react omits it

**Comment by jarek-foksa** [comment]
I have changed the API to `<x-shortcut value="Control+Shift+A">` syntax in Xel version 0.0.44.

**Comment by rockiger** [comment]
Something doesn't seem to work on non apple machines: the modifiers are not shown. The first image is from Linux (same thing for Windows 10) and the second is from a Mac.
![spectacle f20770](https://user-images.githubusercontent.com/458677/27887587-c5b27dec-61e1-11e7-9faf-eafcdf077b98.png) 
![spectacle t20770](https://user-images.githubusercontent.com/458677/27887730-8d5ad164-61e2-11e7-8880-17d386dce59b.png)

**Comment by jarek-foksa** [comment]
@rockiger This should be now fixed in version 0.0.48.

**Comment by rockiger** [comment]
Works like a charm now!

Thanks a lot!

**Comment by a-y-u-s-h** [comment]
How do you use it in React? What do I need to import from xel to make it work?

**Comment by jarek-foksa** [comment]
@a-y-u-s-h Please check the instructions on https://xel-toolkit.org/setup
