### ISSUE TITLE
declaration for iconset default possible?

### ISSUE THREAD

**Issue by sandor** [jarek-foksa/xel#30]
Hey,

I am constructing a tab menu with icons in angular wit ng-repeat. Some of the icons are using the default iconset and some not. I would like to get my icons via my controller like this:
`{
			title: 'Four',
			url: 'templates/style_menu.html',
			ticon: 'style',
			custom: ''
    }, {
			title: 'Five',
			url: 'templates/text_menu.html',
			ticon: 'text',
			custom: 'images/icons.svg'
    },`

Where custom would be the path to the custom iconset:

`<x-button ng-repeat="tab in tabs" skin="tabnav" ng-class="{active:isActiveTab(tab.url)}" 
                ng-click="onClickTab(tab)">
								<x-icon name="{{tab.ticon}}" iconset={{tab.custom}}></x-icon>
							</x-button>`

My problem: If I am leaving the iconset="" – empty the default icons are not showing up.

So short question: is it somehow possible to declare iconset="default"

**Comment by jarek-foksa** [comment]
This should be fixed in version 0.0.45, `iconset=""` should have the same effect as no `iconset` attribute, i.e. default icons should be used.
