### ISSUE TITLE
Hide and Recover Menu for Printing

### ISSUE THREAD

**Issue by rdemo** [jarek-foksa/xel#31]
I've attempted to hide the menu for printing purposes in an electron app.  I've done it by wrapping the menu elements in a div and hiding it, and with CSS @media to hide the div for printing.  Either way, it works fine for printing but the menu is no longer active when I show it again.  

Anything I need to do differently?

**Comment by jarek-foksa** [comment]
Please provide a sample code that will allow me to reproduce this issue.

**Comment by jarek-foksa** [comment]
Xel project underwent a major rewrite recently. If you can still reproduce this issue, please report it on https://xel-toolkit.org/issues.
