### ISSUE TITLE
x-input file

### ISSUE THREAD

**Issue by ensiform** [jarek-foksa/xel#33]
A themed file selection input currently does not seem to exist.  You can manually specify file as a type to x-input but it doesn't seem to fit with themes.  Alternative would be to have the file input its own separate type.

**Comment by jarek-foksa** [comment]
I think this should be implemented as a separate widget called `<x-fileinput>` because it's going to have significantly different API from `<x-input>`. I did not add support for "file" type to `<x-input>` intentionally, it's a bug (please don't rely on it).

**Comment by jarek-foksa** [comment]
With the new Native File System API it does not make sense anymore to provide a separate file input widget.
