### ISSUE TITLE
jQuery check if checkbox is checked

### ISSUE THREAD

**Issue by matejmosko** [jarek-foksa/xel#34]
Hello, I am stuck on a problem with your x-checkbox. I have tried all of the following methods to check if checkbox is checked but with no success. Does x-checkbox act like a checkbox?

$('#checkbox').is(":checked")
$('#checkbox').prop('checked')
$('#checkbox')[0].checked
$('#checkbox').get(0).checked

When I replace your x-checkbox with normal input type='checkbox' these methods work as expected.

**Comment by jarek-foksa** [comment]
You should use `toggled` property/attribute, not `checked`. I didn't follow the HTML API naming conventions here because I wanted it to be consistent with `<x-radio>` and `<x-switch>` elements which have very similar purpose.

**Comment by matejmosko** [comment]
Thank you. It would be great to create a HTML API fallback. Or at least mention this incomaptibility at xel-toolkit.org.

**Comment by jarek-foksa** [comment]
The new project website now documents the JavaScript API for each element.
