### ISSUE TITLE
x-numberinput – not able to set to "0"

### ISSUE THREAD

**Issue by sandor** [jarek-foksa/xel#39]
I am getting and setting the values for my x-numberinput with JS. Working fine when I get values like 1,2,3  ... 100 etc. (also no problem with negative values. But when I am receiving "0" (zero) the value is not displayed in the x-numberinput. Typing manually "0" in the input ist working. I think I am missing something obvious... ?

**Comment by jarek-foksa** [comment]
I'm unable to reproduce this bug. Could you please provide some sample code (without framework-specific stuff)?

**Comment by sandor** [comment]
Sorry Jarek! My big problem is, that I still have to use some framework specific stuff to describe the issue, since I am working with some Fabric.js canvas elements (and as always with AngularJS – sorry!). Recreating a test case without this frameworks will not be of use for my case – especially if you are not able to reproduce the case without using framework stuff. 

Not sure if such a case can even be recreated without a framework:

1. create an object on the canvas with JS and assign a property like 'width' or "angle"
2. get the specific property (width/angle) and bind it to an x-numberinput in your HTML file so that the width/angle values of the created object are reflected in there
3. now try to use the a value "0"

Does this making sense?

**Comment by sandor** [comment]
@jarek-foksa – I have found a solution for this problem. I was writing the specific value like this:

`angle: 0,`

Writing the value like this will solve the problem:

`angle: '0',`

You can close the issue if you like – unless it is still relevant...

**Comment by jarek-foksa** [comment]
As far as I'm concerned, I have no plans for working on issues that require digging into the internals of Angular. But let's keep this open in case someone else is interested in fixing it.

**Comment by sandor** [comment]
Yeah, it is OK and I understand totally that you don't have any plans (or time) to do something angular specific here. Just hope that it is OK when I post/ask something that is not so clearly Angular specific (or some other stupid stuff that a non-coder like me can ask). So please: if the question or the post is to stupid – just ignore it.   :-)

**Comment by jarek-foksa** [comment]
As long as the issue is somehow related to Xel and states the problem clearly I'm perfectly fine with it. When I ignore a question, it's usually because I don't know the answer.

**Comment by sandor** [comment]
OK, so we are cool. Just have some patience with me please :-)

**Comment by jarek-foksa** [comment]
Xel project underwent a major rewrite recently. If you can still reproduce this bug, please report it on https://xel-toolkit.org/issues.
