### ISSUE TITLE
input/numberinput not updating value on blur (click)

### ISSUE THREAD

**Issue by haroldiedema** [jarek-foksa/xel#40]
I have a form with a couple of number inputs.

If I change the value of a numberinput, then click the submit button while the number input is still focused, the updated value is not retrievable using jQuery.

However, if I focus the number input and press the TAB key to get out of it, the value gets updated and I can retrieve the value using `$('x-numberinput').val()`.

Is there a workaround for this that I can use?

**Comment by jarek-foksa** [comment]
I have added an ugly fix for now.  In the longer run the current approach to focus management will have to reworked from scratch.

**Comment by haroldiedema** [comment]
Thank you very much! 👍
