### ISSUE TITLE
Dockable layout support for tabs

### ISSUE THREAD

**Issue by janinurminen** [jarek-foksa/xel#42]
It would be nice to have docking / dockable layout support for tabs since it is quite common component for desktop app UIs.

**Comment by jarek-foksa** [comment]
I'm not sure how dockable layout should look and work. Do you mean something like pinned tabs from Chrome?

**Comment by janinurminen** [comment]
I meant something like this: http://phosphorjs.github.io/examples/dockpanel/

You can have tabs which can be dragged around, organised in groups etc. This functionality would make editor like application UI development easy and quick.

**Comment by jarek-foksa** [comment]
I'm sorry, but I have no plans for implementing this as it would mean introducing even more complexity to `<x-doctabs>` component and as far as I'm concerned I consider this type of layout to be an anti-pattern.
