### ISSUE TITLE
Allow source to be bundled

### ISSUE THREAD

**Issue by nikolay-borzov** [jarek-foksa/xel#43]
Currently js requires `link` tag with theme.
```
let theme = document.querySelector('link[href*=".theme.css"]').getAttribute("href");
```
Also there is `XelAppElement` class in the source that looks like xel demo

**Comment by jarek-foksa** [comment]
NPM package already has all JS and CSS files (except themes) bundled into `xel.min.js` file.

Custom elements with "xel-" prefix ("xel-app", "xel-demo", "xel-codeview") are private and used exclusively by the demo site.

**Comment by nikolay-borzov** [comment]
Right, but how can I bundle `material.theme.css` into my css bundle?

**Comment by jarek-foksa** [comment]
The only supported way to use Xel is the one described in README.md. Due to the issues associated with handling relative URLs I have no plans for supporting any other usage scenarios.

**Comment by nikolay-borzov** [comment]
Got it. Thanks
