### ISSUE TITLE
Visual glitch in Accordion with Material Theme

### ISSUE THREAD

**Issue by cjgriscom** [jarek-foksa/xel#53]
I am experiencing a visual bug with my Drawer/Accordion configuration.  It seems applicable only to the Material stylesheet.  When the page loads, the carat symbol jumps out of frame, but snaps into place once the user interacts with it.

The below animation shows the bug occurring in an Electron app:
![xelbug](https://user-images.githubusercontent.com/3923105/33956672-44d24770-e00d-11e7-8b63-e7c5834a92d0.gif)

The bug also occurs in the attached HTML document running in Chromium.
![xelbugchrome](https://user-images.githubusercontent.com/3923105/33956682-4d76d9c2-e00d-11e7-9959-8bcc22a717cd.png)

My Chromium version is: Version 63.0.3239.84 (Developer Build) (64-bit)
Electron version v1.6.15

```HTML
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bug Report</title>
    <link rel="stylesheet" href="node_modules/typeface-noto-sans/index.css">
    <link rel="stylesheet" href="node_modules/typeface-roboto-mono/index.css">
    <link rel="stylesheet" href="node_modules/typeface-roboto/index.css">
    <link rel="stylesheet" href="node_modules/xel/stylesheets/material.theme.css">
    <script src="node_modules/xel/xel.min.js"></script>
  </head>
  <body>
    <div id="app">
      <x-drawer id="drawer">
        <x-accordion>
            <header>
              <x-label>Accordion1</x-label>
            </header>
            <main>
            <x-label>Chrome Example</x-label>
                <x-input value="Accordion1"></x-input>
                <x-button>
                <x-label>Button</x-label>
                </x-button>
            </main>
        </x-accordion>
        <hr>
      </x-drawer>
      <h1>Bug Report</h1>
      <x-box>
        <x-progressbar></x-progressbar>
        <x-button onclick="document.querySelector('#drawer').opened = true" id="button_drawer">
            <x-label>Open</x-label>
        </x-button>
      </x-box>
    </div>
  </body>
</html>

```

**Comment by jarek-foksa** [comment]
Can you reproduce this issue with Xel 0.0.82?

**Comment by cjgriscom** [comment]
It appears to be fixed!  Thank you for your quick response.

**Comment by jarek-foksa** [comment]
BTW, keep in mind I might deprecate `<x-drawer>` in favor of the standard `<dialog>` in near future.
