### ISSUE TITLE
Problem to load icons

### ISSUE THREAD

**Issue by madpwn** [jarek-foksa/xel#55]
Hello Ive got a problem with x-icons

I cannot use icons on "file" URLs. But it is important because I'm going to create an electron application. I've tried out many things that I've found with google to solve it but none of them works.

The HTML looks like this, and Yes I did include the xel files in the right order etc.
`    <x-button>
        <x-icon name="expand-less"></x-icon>
      </x-button>`

But the console throws  this error: 
`Unsafe attempt to load URL file:///G:/Projects/Web/James%20-%20AI/App/src/renderer/node_modules/xel/images/icons.svg#expand-less from frame with URL file:///G:/Projects/Web/James%20-%20AI/App/src/renderer/index.html. 'file:' URLs are treated as unique security origins.`

**Comment by madpwn** [comment]
Yes I know that this Path "file:///G:/Projects/Web/James%20-%20AI/App/src/renderer/node_modules/xel/images/icons.svg" is the wrong . I already tried it in a fresh project with the html in the root. It didnt work too

**Comment by jarek-foksa** [comment]
Please run `npm install xel@0.0.88` and let me know if you still observe this issue.

**Comment by jarek-foksa** [comment]
As a side note, this might break again in Electron 2.0.0: https://github.com/electron/electron/issues/9474
