### ISSUE TITLE
Firefox!

### ISSUE THREAD

**Issue by gka** [jarek-foksa/xel#61]
> _To view this site, you must use Chrome, Opera or other Chromium-based browser._

Are you kidding me, Opera is supported but Firefox is not? 

Is there seriously something lacking in Firefox to support Xel components?

**Comment by jarek-foksa** [comment]
Supporting Firefox would mean a lot of overhead associated with handling Firefox-specific bugs and would prevent me from using new APIs that land in Chromium. In my opinion it is not worth the effort as the primary target for this widget toolkit is Electron runtime.
