### ISSUE TITLE
Unexpected token function

### ISSUE THREAD

**Issue by Jaliborc** [jarek-foksa/xel#63]
On one of my Windows 10 machines, I'm getting the following error when trying to include the javascript file:

    xel.min.js:15 Uncaught SyntaxError: Unexpected token function

I've tried using both the recommended node version 7.9 and the latest 9.4.

**Comment by jarek-foksa** [comment]
What version of Electron are you using? It looks like you are using some older version that does not support async/await.

**Comment by Jaliborc** [comment]
Yes, that was it. My bad. Saw someone talking about older versions not supporting it and misunderstood they were talking about he Node version.

Working now that I updated Electron.
