### ISSUE TITLE
Mac OS Theme Enhancement

### ISSUE THREAD

**Issue by sksar** [jarek-foksa/xel#65]
Mac OS theme elements are all slightly gradient and also they contain a very subtle box-shadow underneath most UI Form elements, like Select and Buttons. Also there are inner shadows in radio and checkbox.

Here's an Image for reference:
![image](https://user-images.githubusercontent.com/11752260/36343937-f9f62810-1438-11e8-8e8c-ec2774449d86.png)

Please add the proper outer shadows and also the inner shadows.

**Comment by jarek-foksa** [comment]
AFAIR I added some shadows to radios and checkboxes, but I'm not sure whether they match exactly the native widgets. Fixing this is not my top priority right now, but if someone submits a pull request I will accept it.

**Comment by jarek-foksa** [comment]
Xel 0.9 now implements the latest macOS HIG.
