### ISSUE TITLE
Throbber Element not loading with ASAR package

### ISSUE THREAD

**Issue by cckelly** [jarek-foksa/xel#68]
Just like the title says, I'm trying to load the throbber element in a packaged build but it fails. My first thought was that the image needs to be unpacked which I did like so in the elctron-packager config:

```
"asar": {
  "unpackDir": "node_modules/{xel,node-notifier}/**/**/*"
},
```
The `ring-throbber.svg` throws an `ERR_FAILED` and I believe it's because the resolved path points to the `app.asar` packaged instead of the `app.asar.unpacked` directory. Is there anyway xel can check if the file exists in the unpacked directory?

**Comment by jarek-foksa** [comment]
This should be fixed in version 0.0.126.
