### ISSUE TITLE
Javascript Documentation for x-doctabs

### ISSUE THREAD

**Issue by WetDesertRock** [jarek-foksa/xel#69]
It seems like there should be some sort of documentation for x-doctabs (and probably x-tabs).
I'd imagine there should be some sort of documentation for adding, removing and switching tabs. I'd also imagine there would be events corresponding to these events.

On a side note, is it possible to remove the + button in the doctabs?

**Comment by jarek-foksa** [comment]
Yeah, the documentation is missing but you should be able to figure most things from the source code.

By default the "+" button opens a dummy new tab. You want to prevent that and instead create and open your own tab with custom title and other properties:

```js
let {html} = Xel.utils.element;
let tabs = document.querySelector("x-doctabs");

tabs.addEventListener("open", (event) => {
  // Don't open the default dummy tab
  event.preventDefault();

  // Create and open a new custom tab
  {
    let label = "Tab 1";

    let tab = html`
      <x-doctab selected>
        <x-label>${label}</x-label>
      </x-doctab>  
    `;

    tabs.openTab(tab);
  }
});
```

You should be also listening for "close" and "select" events on `<x-doctabs>` and update the corresponding views accordingly.

**Comment by jarek-foksa** [comment]
To hide the "+" button, you could use following CSS rule:

```css
  x-doctabs {
    --open-button-width: 0;
    --open-button-height: 0;
    --open-button-margin: 0;
  }
```

**Comment by WetDesertRock** [comment]
How do I get access to the Xel object? I haven't been able to find a way. Do I need to repackage xel without iife? This is the HTML I'm using:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>Hello World!</title>
		<link rel="stylesheet" href="./node_modules/xel/stylesheets/vanilla.theme.css">
		<script src="./node_modules/xel/xel.min.js"></script>
		<script>
			console.log("Xel:", Xel);
		</script>
	</head>
	<body>
		<x-button>Hello World</x-button>
	</body>
</html>
```

**Comment by jarek-foksa** [comment]
I'm sorry, I forgot that global Xel object was removed during the recent migration to ES6 modules. Instead of:

```js
let tab = html`
  <x-doctab>
    <x-label>Tab 1</x-label>
  </x-doctab>  
`;
```

You could use plain DOM methods:

```js
let tab = document.createElement("x-doctab");
tab.innerHTML = "<x-label>Tab 1</x-label>";
```

**Comment by bgokcol** [comment]
If you want to hide "x" (close) button, you can use this code:
`
        x-doctab {
            --close-button-width: 0;
            --close-button-height: 0;
            --close-button-margin: 0;
        }
`

**Comment by jarek-foksa** [comment]
I updated the documentation on https://xel-toolkit.org/elements/x-doctabs
