### ISSUE TITLE
x-select mouse wheel scroll very slow

### ISSUE THREAD

**Issue by mastercoms** [jarek-foksa/xel#75]
**Observed behavior**

When expanded, `x-select` scrolls very slowly and tries to expand to a full height at certain window sizes.

**Expected behavior**

`x-select` either starts at the full height or scrolls at the proper speed.

**Reproduction steps**

Create an `x-select` with some elements and then resize the vertical height of the window to just almost not have enough room. For example on the [demo page](https://xel-toolkit.org/elements/x-select), I used a vertical height of 250px. Then click the `x-select` to expand it and try to scroll with the mouse wheel.

**Information**

Version: 0.0.141
Platform: Windows and Linux Electron 2.0.4

**Comment by jarek-foksa** [comment]
I'm unable to reproduce this issue on macOS, could you please provide an animated GIF or a video recording demonstrating it?

**Comment by mastercoms** [comment]
https://i.imgur.com/kkqxSke.gifv

Here is a GIF on Chrome using the demo page, 250px height.

**Comment by jarek-foksa** [comment]
I followed the exact steps using a trackpad but I couldn't reproduce the bug: https://youtu.be/eOmcKi7Cb0k

Perhaps it happens only when using a mouse wheel?

**Comment by 23phy** [comment]
Any updates on this? 
I can still reproduce it in the demo page, the [x-select](https://xel-toolkit.org/elements/x-select) section.
Something I noticed, as you can see in the gif underneath, is that after a certain amount of slow scrolling, it reverts back to normal, also getting to the top of the list, no longer scrolls slow.
![xel](https://user-images.githubusercontent.com/11774416/47467621-07f69400-d800-11e8-8b44-aa454033d6ac.gif)

**Comment by jarek-foksa** [comment]
I was unable to reproduce this issue and I'm not really sure what could be causing it. If someone is interested in fixing it, the scrolling behavior is implemented [here](https://github.com/jarek-foksa/xel/blob/fd04dc90832bce37dd954cec5f1e1048616424ce/elements/x-menu.js#L931-L964).

**Comment by Septh** [comment]
The issue is still present.

As @23phy's gif shows, first the menu's height slowly grows and then only when the menu fills the whole window height does the scroll happen.

I'm not sure what's going on here, but the whole `_onScroll()` function seems to be at fault. If I insert a return statement here with DevTools (see pic below) then the function does nothing and the component works just fine.

![xselect](https://user-images.githubusercontent.com/11949623/50745060-642a5b00-1228-11e9-85b2-24323e2d3d3d.png)

**Comment by jarek-foksa** [comment]
I managed to reproduce this bug using either a trackpad or a mouse on a Windows 10 running in a virtual machine.

This seems to be a Chrome bug, but I have implemented a workaround in Xel version 0.0.191.
