### ISSUE TITLE
yarn add xel doesn't work properly

### ISSUE THREAD

**Issue by mmakrzem** [jarek-foksa/xel#76]
I use yarn (as opposed to npm) to get packages.  If I call yarn add xel to grab all your files from github, I only get themes/*, package.json and xel.min.js.  All the other files are missing!  If I use npm install xel I do get all the other files.

Any idea on how to fix this?  My toolchain requires yarn to be used as npm corrupts my setup.

**Comment by jarek-foksa** [comment]
I have never used yarn before, but isn't `yarn add xel` grabbing the files from the NPM registry rather than Github?

Anyway, I suspect this could be a bug in the yarn package manager rather than Xel: https://github.com/yarnpkg/yarn/issues/3169

**Comment by mmakrzem** [comment]
Thank you, that solved the problem.
