### ISSUE TITLE
Provide a list of all available icons on xel-toolkit.org/elements/x-icon page

### ISSUE THREAD

**Issue by mmakrzem** [jarek-foksa/xel#77]
@jarek-foksa is there a help page or something that illustrates all the icons which are available in xel?  I opened the icons.svg file and I see that there are 964 icons defined, but what do they all look like?  It would be nice to see their pictures and names side by side so that it is easy to choose what is needed.

**Comment by jarek-foksa** [comment]
You can browse the icons on https://material.io/tools/icons/, just replace "_" with "-" in icon name, e.g. use `<x-icon name="help-outline">`, not `<x-icon name="help_outline">`.

**Comment by mmakrzem** [comment]
The new browse link (https://material.io/icons/) on the document page is great!

**Comment by danyhoron** [comment]
Hi,
I noticed that not all the material icons work.
An example is: https://material.io/resources/icons/?search=screen&icon=cancel_presentation&style=baseline

Do I need to do anything special to make it work ?

Thank you

**Comment by jarek-foksa** [comment]
Material iconset shipped with Xel 0.0.x is a bit outdated. The stable version of Xel (to be released soon) is going to contain only ~200 most commonly used Material and Fluent icons for the testing purposes.

**Comment by danyhoron** [comment]
Thank you for that.

Can I use other icons not shipped w/ Xel?

**Comment by jarek-foksa** [comment]
Yes, for best performance you should define your own iconset that contains only the icons used by your app. Then you could reference it like this: `<x-icon name="zoom" iconset="/iconsets/custom.svg"></x-icon>`

**Comment by danyhoron** [comment]
Great!

Thank you. You've done an awesome job.
