### ISSUE TITLE
x-numberinput does not respect min and max values always

### ISSUE THREAD

**Issue by mmakrzem** [jarek-foksa/xel#79]
I created a number input field like this:

```
<x-numberinput min="1" max="9">
</x-numberinput>
```

I can put focus inside the input field with my mouse and type in a number outside the max/min range and the input field continues to show the value I entered even when I move my focus out of the input field.  ie 4575.  Sometimes if I click inside and then out again, the number value changes to fit in the range ie 9, but most of the time, the min and max values are not respected.

i'd like to listen to events when this value changes, but not when I type.  Only when I leave the input field.  I'm currently using inputEl.addEventListener( 'focusout', () => {} ); for this.  However once this bug is fixed, will focusout still work.  ie will it report to me the correct clamped value?

**Comment by jarek-foksa** [comment]
This bug should be fixed in version 0.0.153, please reopen the issue if you can still reproduce it.

**Comment by mmakrzem** [comment]
looks good!
