### ISSUE TITLE
Closing Dialog box

### ISSUE THREAD

**Issue by Rohit-Metapercept** [jarek-foksa/xel#83]
Hi , I am using dialog box   and  I am not getting any way to close the dialog box on button click . Is there any way to close it without on pointer event?

**Comment by jarek-foksa** [comment]
You should use `dialog.close()` method.

**Comment by Rohit-Metapercept** [comment]
I tried this but it's not getting close

`<footer>
				  <x-button id="disagree-button" ng-click="dialog.close()">
					<x-label>Cancel</x-label>
				  </x-button>
				  <x-button toggled id="agree-button" ng-click="fronmatter_default();">
					<x-label>Confirm</x-label>
				  </x-button>
				</footer>`

**Comment by jarek-foksa** [comment]
Does this work for you?

```js
let button = document.querySelector("x-button#disagree-button");
let dialog = document.querySelector("dialog");

button.addEventListener("click", (event) => {
  dialog.close();
});
```

**Comment by Rohit-Metapercept** [comment]
Yes this worked for me. Thanks,  got the idea.
