### ISSUE TITLE
Drawer/Side menu API?

### ISSUE THREAD

**Issue by Jarrio** [jarek-foksa/xel#84]
The README says that this has drawer support but there doesn't appear to be any API for it on docs even though the demo has a side menu, an example of the code for the side menu would be appreciated - thanks!

**Comment by jarek-foksa** [comment]
To implement a drawer, you should use a standard `<dialog>` element. Check the "Left side drawer" and "Right side drawer" examples on https://xel-toolkit.org/elements/dialog

**Comment by Jarrio** [comment]
Ah, I appreciate that. I would like to mention that pretty much all of these dialog's seem to be impossible to close when triggering them as there is no close button visible to actually press - ESC, enter or clicking the background does not trigger the dialog to close either.

I am using Chrome `Version 71.0.3578.98 (Official Build) (64-bit)`

**Comment by jarek-foksa** [comment]
Are you still unable to close the dialogs by clicking the backdrop with Xel version 0.0.179 (I published it several minutes ago).

**Comment by Jarrio** [comment]
Yes, this fixed the issue. Thanks!

**Comment by jarek-foksa** [comment]
To close a dialog with Esc key:

```js
dialog.addEventListener("keydown", (event) => {
  if (event.code === "Escape") {
    dialog.close();
  }
});
```

**Comment by Jarrio** [comment]
How do you have the dialog open by default? Setting the button to `toggled` doesn't seem to work as expected. The button is toggled but the drawer remains closed

**Comment by jarek-foksa** [comment]
You should use `button.expand()` method.
