### ISSUE TITLE
HTML Imports was deprecated

### ISSUE THREAD

**Issue by nom3ad** [jarek-foksa/xel#88]
Chrome and chromium based browsers are dropping support for html imports.

reference: https://www.chromestatus.com/feature/5144752345317376

> HTML Imports are deprecated at M70, and will be removed in M73, around, April 2019.

And follwing check for supported browser going to fail.

https://github.com/jarek-foksa/xel/blob/1b679334e20ee5078b8c78ddd7090800480a6d67/index.html#L36-L48

**Comment by nom3ad** [comment]
Hey, Thanks for the quick fix. 
finally, I was able to xel run on `Firefox`.
A lot of bugs though. But many components work properly with the vanilla theme.

**Comment by jarek-foksa** [comment]
I'm afraid Xel is unlikely to support Firefox anytime soon. Proper support would require adding a lot of special casing which I would prefer to avoid.
