### ISSUE TITLE
stop contextmenu from swallowing events

### ISSUE THREAD

**Issue by prog-r-amer** [jarek-foksa/xel#90]
Hi,

I'd like to still be able to get information from the mousemove event while the x-contextmenu is open, how can I do this?

Greetings,
Tobias

**Comment by jarek-foksa** [comment]
I can't reproduce this issue. On which element are you listening for mouse events?

**Comment by prog-r-amer** [comment]
on the parent element, if you don't manage to reproduce I can send you a basic example

**Comment by jarek-foksa** [comment]
Please publish a basic example on https://gist.github.com

**Comment by prog-r-amer** [comment]
you were right, usually it's a non issue.

for my case however I need to use contextmenu together with canvas, and that's where the problem comes in.

https://gist.github.com/prog-r-amer/a45cc8569e186ad1a565eed33ad4c473

Also doesn't work if I wrap the canvas.

**Comment by jarek-foksa** [comment]
Thanks, I can reproduce it now. For now I would recommend you to avoid using `<x-contextmenu>` element as its API was not really well thought out and it has major issues when it comes to z-index positioning.

You could achieve similar effect using just `<x-menu>` element with some additional event handlers, here is an example: https://gist.github.com/jarek-foksa/fd67b58472492f722576bdbfa62e68b0

**Comment by prog-r-amer** [comment]
Thanks a lot, that works well.
